on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-2019]
        extras: [noextras, pytorch, foolbox, cleverhans]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install with extras
      if: ${{ matrix.extras != 'noextras' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
        python -m pip install -e .[unittests,${{ matrix.extras }}]
    - name: Install noextras
      if: ${{ matrix.extras == 'noextras' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
        python -m pip install -e .[unittests]
    - name: Test with pytest
      run: |
        pytest
