
name: run tests on demand on multiple platforms

on:
  push:
    branches:
     - '!master'
     - '!develop'

jobs:
  build:
    if: "contains(${{ github.event.head_commit.message }}, '[runtests]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pytest
